### ISSUE TITLE
Matchfirst not iterable during data processing

### ISSUE THREAD

**Issue by elaruwan** [salesforce/TabularSemanticParsing#24]
Hello,

When preprocessing the data via ./experiment-bridge.sh configs/bridge/spider-bridge-bert-large.sh --process_data 0

I found this error - as 
TypeError: argument of type 'MatchFirst' is not iterable

This comes from moz_sp/formatting.py as it attempts to check the incoming identifier against the set of RESERVED names, however as these are infact pyparsing objects, they aren't iterable.  I tries this via 'identifier not in RESERVED'.
https://pythonhosted.org/pyparsing/pyparsing.MatchFirst-class.html

It appears that 'not RESERVED.searchString(identifier)' may solve this issue?

I'm using python 3.8
pyparsing==2.4.7

**Comment by todpole3** [comment]
@elaruwan It could be a difference between python3.7 and 3.8. In our experiments we used Python 3.7.

**Comment by elaruwan** [comment]
Ah,

Thats likely!

Will close

**Comment by elaruwan** [comment]
Thanks!
