### ISSUE TITLE
Support for GraPPA?

### ISSUE THREAD

**Issue by awasthiabhijeet** [salesforce/TabularSemanticParsing#27]
Hi @todpole3!

Thanks for open-sourcing this project.

I wanted to know if the pre-trained [GRAPPA checkpoints](https://huggingface.co/Salesforce/grappa_large_jnt) are compatible with this code-base?

**Comment by todpole3** [comment]
You can load GRAPPA via the huggingface API like we did for BERT. To do so you also need to change the special token settings to match that used by GRAPPA, which is the same as RoBERTa.
