### ISSUE TITLE
What do top-1 top-2 top-3 top-5 exact match mean when the model do inferencing?

### ISSUE THREAD

**Issue by wangshushu0213** [salesforce/TabularSemanticParsing#31]
When I do the inference comand, I received the following results. But I do not know what do top-1 top-2 top-3 top-5 exact match mean and how to get the exact match and exe match metrics on dev and test dataset?
![bridge dev](https://user-images.githubusercontent.com/83213834/116101707-a4a39080-a6e0-11eb-9dac-4e2605d68557.png)
![bridge test](https://user-images.githubusercontent.com/83213834/116101730-a9684480-a6e0-11eb-91e5-cf567d72d6d9.png)

**Comment by todpole3** [comment]
We use beam search decoding. top-k exact match is computed by counting the prediction to an example as correct as long as any of the top-k generations decoded with beam search exactly matches the ground truth reference.
