### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by mengxun1437** [salesforce/TabularSemanticParsing#33]
hello,can you share me the specific python version  you use when developing?3.4 ,3.6,3.7 or some else.I get a problem and i guess that caused by the python version.
**here is the detail error:**
```shell
 WARNING: Building wheel for cryptacular failed: [Errno 2] No such file or directory: '/tmp/pip-wheel-zlvdpm39/cryptacular-1.5.5-cp37-abi3-manylinux2010_x86_64.whl'
Failed to build cryptacular
ERROR: Could not build wheels for cryptacular which use PEP 517 and cannot be installed directly
```
Maybe the cryptacular exists with python version,and maybe it can't be install directly ,so i guess the python version  changing can solve it! 
i am freshman to python and AI learning ,excepting your reply 
thanks!

**Comment by todpole3** [comment]
I used Python 3.7
