### ISSUE TITLE
CUDA out of memory on Spider

### ISSUE THREAD

**Issue by realningzheng** [salesforce/TabularSemanticParsing#36]
Hi,

Thanks for sharing the code. I found when training on Spider, CUDA out of memory error keeps occuring even though I have set the batch size of both train and dev in parse_args.py to 1. Any idea on that?

![image](https://user-images.githubusercontent.com/60973275/124450435-fcccd200-ddb6-11eb-89f6-696aa78f9885.png)

**Comment by VaheShelunts** [comment]
Hi. I am getting the same cuda error. Did you manage to resolve it?

**Comment by VaheShelunts** [comment]
@realningzheng
