### ISSUE TITLE
Test on Custom Data

### ISSUE THREAD

**Issue by TheurgicDuke771** [salesforce/TabularSemanticParsing#4]
Hi Team,

Thanks for open-sourcing the project. 
I am curious if you can guide me how I can use this framework on my custom data using wikisql model.

Thank you.

**Comment by todpole3** [comment]
If you follow the instruction on WikiSQL in the README you should be able to retrain a model and that performs on the standard WikiSQL benchmark with execution accuracy above 90%.

So an easy start is to split and format your data in the same way as the the standard WikiSQL train/dev/test sets, and run our model. Then you can reconfigure the dataset paths in https://github.com/salesforce/TabularSemanticParsing/blob/main/configs/bridge/wikisql-bridge-bert-large.sh and run our code. 

Notice that there are dataset specific settings in the code and we tell the model which dataset it is using the `dataset_name="wikisql"` parameter. You can either avoid code changing by continuing calling your dataset `wikisql` or replace `wikisql` with your custom dataset name throughout the code.

**Comment by TheurgicDuke771** [comment]
Hi,
I'm able to create the model. But is there any way to test/generate SQL query (like the demo function implementation for spider dataset)
