### ISSUE TITLE
Not all modules are set in requirements.txt

### ISSUE THREAD

**Issue by CrafterKolyan** [salesforce/TabularSemanticParsing#6]
After trying to preprocess data with Spider dataset I get:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/crafterkolyan/workspace/TabularSemanticParsing/src/experiments.py", line 15, in <module>
    import src.data_processor.data_loader as data_loader
  File "/home/crafterkolyan/workspace/TabularSemanticParsing/src/data_processor/data_loader.py", line 15, in <module>
    from src.data_processor.processor_utils import WIKISQL, SPIDER, OTHERS
  File "/home/crafterkolyan/workspace/TabularSemanticParsing/src/data_processor/processor_utils.py", line 13, in <module>
    from moz_sp import denormalize, parse
  File "/home/crafterkolyan/workspace/TabularSemanticParsing/moz_sp/__init__.py", line 25, in <module>
    from mo_future import text, number_types, binary_type, items, string_types
ModuleNotFoundError: No module named 'mo_future'
```

**Comment by CrafterKolyan** [comment]
Seems that's particularly my problem

**Comment by perused** [comment]
> Seems that's particularly my problem

I had this problem in two different environments (local Ubuntu PC, Google CoLab), didn't have the problem at all in a third (used a pro Google CoLab account). 'pip install mo_future' fixed it in the Ubuntu environment.

**Comment by CrafterKolyan** [comment]
@perused you need to set proper python path using:
export PYTHONPATH=`pwd`

The thing I understood is that you should.exactly follow the steps in README.md without skipping anything

**Comment by perused** [comment]
I'm using Google CoLab, and the following two attempts still give me the moz_sp error:
1. %env PYTHONPATH=`pwd`
2. import os
   

> @perused you need to set proper python path using:
> export PYTHONPATH=`pwd`
> 
> The thing I understood is that you should.exactly follow the steps in README.md without skipping anything

Thanks for the response.

I'm trying to replicate this code on Google CoLab. I still get the moz_sp error even when trying:

%env PYTHONPATH=`pwd`

and also

import os
os.environ['PYTHONPATH'] = "pwd"

any ideas on this? Much appreciated

**Comment by CrafterKolyan** [comment]
You should execute `pwd` command. It returns you current directory. Try to set PYTHONPATH to the folder `TabularSemanticParsing`
