### ISSUE TITLE
Run out of memory  when training on collab using GPU

### ISSUE THREAD

**Issue by UsefGamal** [salesforce/TabularSemanticParsing#7]
The module runs out of memory on google collab when training on spider and wikiSQL on both: 
1.while training using the default configuration on 
2. After manipulating the train_batch_size and make it =1 

Also , when trying to run it on my machine 
With GPU Nvidia 1060 max-Q with 6gb 

It also run out of memory.

How can i run it on my machine or on google Collab ? 

And how to run it on another Large Database like adventure works database ?

**Comment by ysymyth** [comment]
also facing OOM using one gpu with 10gb memory. What is the recommended setting to run the default scripts? thanks

**Comment by todpole3** [comment]
Sorry for responding late to this thread.

I was able to reproduce WikiSQL experiments using a GeForce GTX Titan X (12gb memory) using a training batch size of 4.

However, when I try to run Spider experiments on the same GPU, I got OOM exception with batch size 3. I'm currently trying batch size 2 and see if training is able to continue.

I think the best solution for small-mem GPUs is to use multiple of them. Our code does not implement data or parallelization unfortunately and you need to add this part.

**Comment by elaruwan** [comment]
Hi, when running a batch_size=2 accumulated=16, (on spider) I assume we also divide dev batch size by 8 to get 24/8=3?

I am getting this error...


  
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 16000/16000 [2:35:42<00:00,  1.71it/s]
Step 999.9375: average training loss = 0.6869219804488966
  0%|                                                                                                                         | 0/44 [00:00<?, ?it/s]
10622721 pre-computed prediction order reconstruction cached
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/ws/TabularSemanticParsing/src/experiments.py", line 407, in <module>
    run_experiment(args)
  File "/mnt/ws/TabularSemanticParsing/src/experiments.py", line 392, in run_experiment
    train(sp)
  File "/mnt/ws/TabularSemanticParsing/src/experiments.py", line 63, in train
    sp.run_train(train_data, dev_data)
  File "/mnt/ws/TabularSemanticParsing/src/common/learn_framework.py", line 241, in run_train
    output_dict = self.inference(dev_data, restore_clause_order=self.args.process_sql_in_execution_order,
  File "/mnt/ws/TabularSemanticParsing/src/semantic_parser/learn_framework.py", line 209, in inference
    restored_pred, grammatical, schema_consistent = pred_restored_cache[db_name][pred_sql]
ValueError: too many values to unpack (expected 3)
  File "/mnt/ws/TabularSemanticParsing/src/semantic_parser/learn_framework.py", line 209, in inference
    restored_pred, grammatical, schema_consistent = pred_restored_cache[db_name][pred_sql]
ValueError: too many values to unpack (expected 3)

**Comment by elaruwan** [comment]
With batch size 2 on a Tesla T4 with 16GB VRAM you get out of memory errors, trying with a batch size of 1.

**Comment by elaruwan** [comment]
Unfortunately even with a batchsize of 1, if you set num_accumulation_steps to 32 you still run out of memory with a 16GB GPU

python3.6/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA out of memory. Tried to allocate 90.00 MiB (GPU 0; 14.76 GiB total capacity; 13.24 GiB already allocated; 89.75 MiB free; 13.72 GiB reserved in total by PyTorch)
Exception ignored in: <bound method tqdm.__del__ of  48%|█████████████████████████████████████████████████████▍                                                          | 21/44 [08:54<07:58, 20.82s/it]>

**Comment by elaruwan** [comment]
Batch size of 2 might be successful with 12GB of memory.  Training with BS=2 Accumulated=16 and DevBS=3.
Notice theres a spike of memory usage at the beginning.  This is a Telsa T4,  basically a gtx1080 with 16GB of memory
![results](https://user-images.githubusercontent.com/68737042/113781096-468c2900-9784-11eb-90b2-8242469f494b.PNG)
![gpuused](https://user-images.githubusercontent.com/68737042/113781099-47bd5600-9784-11eb-8c8a-14c9d342c47e.PNG)
